module.exports = [
  {
    "username": "Ned_Stark",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Cersei_Lannister",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Tywin_Lannister",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Jon Snow",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Daenerys Targaryen",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Hodor",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
]