module.exports = [
  {
    "username": "Ned_Stark",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Cersei_Lannister",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Tywin_Lannister",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Jon Snow",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Daenerys Targaryen",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Hodor",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Petyr Baelish",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Melisandre",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Joffrey",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
  {
    "username": "Khal Drogo",
    "elo": 1200,
    "games": 0,
    "wins": 0,
    "league": "Westeros",
    "imgLink": "#",
  },
]